Attribute VB_Name = "modIcon"
Option Explicit


Public Const FONT_NAME As String = "Segoe MDL2 Assets"
Private Const TB_ICON As String = "TB_ICON"

Public Enum IconEnums
    icAccept = 1
    icAcceptMedium
    icAccident
    icAccidentSolid
    icAccounts
    icActionCenter
    icActionCenterAsterisk
    icActionCenterMirrored
    icActionCenterNotification
    icActionCenterNotificationMirrored
    icActionCenterQuiet
    icActionCenterQuietNotification
    icAdd
    icAddBold
    icAddFriend
    icAddNewLine
    icAddNewLineFill
    icAddRemoteDevice
    icAddSurfaceHub
    icAddTo
    icAdjustHologram
    icAdmin
    icAirplane
    icAirplaneSolid
    icAlignCenter
    icAlignLeft
    icAlignRight
    icAllApps
    icAllAppsMirrored
    icAnnotation
    icAppIconDefault
    icApplicationGuard
    icApps
    icAreaChart
    icArrowDown8
    icArrowLeft8
    icArrowRight8
    icArrowUp8
    icAspectRatio
    icAsterisk
    icAsteriskBadge12
    icAttach
    icAttachCamera
    icAudio
    icBack
    icBackgroundToggle
    icBackMirrored
    icBackSolidBold
    icBackSpaceQWERTY
    icBackSpaceQWERTYLg
    icBackSpaceQWERTYMd
    icBackSpaceQWERTYSm
    icBackToWindow
    icBadge
    icBandBattery0
    icBandBattery1
    icBandBattery2
    icBandBattery3
    icBandBattery4
    icBandBattery5
    icBandBattery6
    icBank
    icBarcodeScanner
    icBattery0
    icBattery1
    icBattery10
    icBattery2
    icBattery3
    icBattery4
    icBattery5
    icBattery6
    icBattery7
    icBattery8
    icBattery9
    icBatteryCharging0
    icBatteryCharging1
    icBatteryCharging10
    icBatteryCharging2
    icBatteryCharging3
    icBatteryCharging4
    icBatteryCharging5
    icBatteryCharging6
    icBatteryCharging7
    icBatteryCharging8
    icBatteryCharging9
    icBatterySaver0
    icBatterySaver1
    icBatterySaver10
    icBatterySaver2
    icBatterySaver3
    icBatterySaver4
    icBatterySaver5
    icBatterySaver6
    icBatterySaver7
    icBatterySaver8
    icBatterySaver9
    icBatteryUnknown
    icBeta
    icBidiLtr
    icBidiRtl
    icBlockContact
    icBlocked2
    icBlueLight
    icBluetooth
    icBodyCam
    icBold
    icBookmarks
    icBookmarksMirrored
    icBrightness
    icBroom
    icBrowsePhotos
    icBrushSize
    icbug
    icBuildingEnergy
    icBulletedList
    icBulletedListMirrored
    icBullseye
    icBumperLeft
    icBumperRight
    icBus
    icBusSolid
    icButtonA
    icButtonB
    icButtonMenu
    icButtonView2
    icButtonX
    icButtonY
    icCafe
    icCalculator
    icCalculatorAddition
    icCalculatorBackspace
    icCalculatorDivide
    icCalculatorEqualTo
    icCalculatorMultiply
    icCalculatorNegate
    icCalculatorPercentage
    icCalculatorSquareroot
    icCalculatorSubtract
    icCalendar
    icCalendarDay
    icCalendarMirrored
    icCalendarReply
    icCalendarSolid
    icCalendarWeek
    icCallControl
    icCallForwarding
    icCallForwardingMirrored
    icCallForwardInternational
    icCallForwardInternationalMirrored
    icCallForwardRoaming
    icCallForwardRoamingMirrored
    icCalligraphyFill
    icCalligraphyPen
    icCalories
    icCamera
    icCancel
    icCancelMedium
    icCaption
    icCar
    icCaretBottomRightSolidCenter8
    icCaretDownSolid8
    icCaretLeftSolid8
    icCaretRight8
    icCaretRightSolid8
    icCaretUpSolid8
    icCashDrawer
    icCC
    icCellPhone
    icCertificate
    icCharacterAppearance
    icCharacters
    icChatBubbles
    icCheckBox
    icCheckbox14
    icCheckboxComposite
    icCheckboxComposite14
    icCheckboxCompositeReversed
    icCheckboxFill
    icCheckboxIndeterminate
    icCheckboxIndeterminateCombo
    icCheckboxIndeterminateCombo14
    icCheckList
    icChecklistMirrored
    icCheckMark
    icCheveronLeft20
    icCheveronLeft32
    icCheveronRight20
    icCheveronRight32
    icChevronDown
    icChevronDownMed
    icChevronDownSmall
    icChevronLeft
    icChevronLeftMed
    icChevronLeftSmall
    icChevronRight
    icChevronRightMed
    icChevronRightSmall
    icChevronUp
    icChevronUpMed
    icChevronUpSmall
    icChineseBoPoMoFo
    icChineseChangjie
    icChinesePinyin
    icChinesePunctuation
    icChineseQuick
    icChipCardCreditCardReader
    icChromeAnnotate
    icChromeAnnotateContrast
    icChromeBack
    icChromeBackContrast
    icChromeBackContrastMirrored
    icChromeBackMirrored
    icChromeBackToWindow
    icChromeBackToWindowContrast
    icChromeClose
    icChromeCloseContrast
    icChromeFullScreen
    icChromeFullScreenContrast
    icChromeMaximize
    icChromeMaximizeContrast
    icChromeMinimize
    icChromeMinimizeContrast
    icChromeRestore
    icChromeRestoreContrast
    icChromeSwitch
    icChromeSwitchContast
    icCHTLanguageBar
    icCircleFill
    icCircleFillBadge12
    icCircleRing
    icCircleRingBadge12
    icCircleShapeSolid
    icCityNext
    icCityNext2
    icClear
    icClearAllInk
    icClearAllInkMirrored
    icClearSelection
    icClearSelectionMirrored
    icClick
    icClickedOutLoudSolidBold
    icClickSolid
    icClipboardList
    icClipboardListMirrored
    icClippingTool
    icClosePane
    icClosePaneMirrored
    icCloud
    icCloudPrinter
    icCloudSearch
    icCode
    icCollapseContent
    icCollapseContentSingle
    icCollateLandscape
    icCollateLandscapeSeparated
    icCollatePortrait
    icCollatePortraitSeparated
    icColor
    icColorOff
    icColorSolid
    icCommaKey
    icCommandPrompt
    icComment
    icCommunications
    icCompanionApp
    icCompanionDeviceFramework
    icCompleted
    icCompletedSolid
    icComponent
    icComposeMode
    icConnect
    icConnectApp
    icConnected
    icConstruction
    icConstructionCone
    icConstructionSolid
    icContact
    icContact2
    icContactInfo
    icContactInfoMirrored
    icContactPresence
    icContactSolid
    icCopy
    icCopyTo
    icCourthouse
    icCrop
    icCtrlSpatialLeft
    icCtrlSpatialRight
    icCut
    icDashKey
    icDataSense
    icDataSenseBar
    icDateTime
    icDateTimeMirrored
    icDefaultAPN
    icDefenderApp
    icDefenderBadge12
    icDelete
    icDeleteLines
    icDeleteLinesFill
    icDeleteWord
    icDeleteWordFill
    icDeliveryOptimization
    icDesign
    icDetachablePC
    icDeveloperTools
    icDeviceDiscovery
    icDeviceLaptopNoPic
    icDeviceLaptopPic
    icDeviceMonitorLeftPic
    icDeviceMonitorNoPic
    icDeviceMonitorRightPic
    icDevices
    icDevices2
    icDevices3
    icDevices4
    icDevUpdate
    icDiagnostic
    icDial1
    icDial10
    icDial11
    icDial12
    icDial13
    icDial14
    icDial15
    icDial16
    icDial2
    icDial3
    icDial4
    icDial5
    icDial6
    icDial7
    icDial8
    icDial9
    icDialpad
    icDialShape1
    icDialShape2
    icDialShape3
    icDialShape4
    icDialUp
    icDictionary
    icDictionaryAdd
    icDictionaryCloud
    icDirectAccess
    icDirections
    icDisableUpdates
    icDisconnectDisplay
    icDisconnectDrive
    icDislike
    icDMC
    icDock
    icDockBottom
    icDockLeft
    icDockLeftMirrored
    icDockRight
    icDockRightMirrored
    icDocument
    icDoubleLandscape
    icDoublePinyin
    icDoublePortrait
    icDown
    icDownload
    icDownloadMap
    icDownShiftKey
    icDpad
    icDraw
    icDrawSolid
    icDrivingMode
    icDrop
    icDullSound
    icDullSoundKey
    icDuplexLandscapeOneSided
    icDuplexLandscapeOneSidedMirrored
    icDuplexLandscapeTwoSidedLongEdge
    icDuplexLandscapeTwoSidedLongEdgeMirrored
    icDuplexLandscapeTwoSidedShortEdge
    icDuplexLandscapeTwoSidedShortEdgeMirrored
    icDuplexPortraitOneSided
    icDuplexPortraitOneSidedMirrored
    icDuplexPortraitTwoSidedLongEdge
    icDuplexPortraitTwoSidedLongEdgeMirrored
    icDuplexPortraitTwoSidedShortEdge
    icDuplexPortraitTwoSidedShortEdgeMirrored
    icDynamicLock
    icEar
    icEarbud
    icEaseOfAccess
    icEdit
    icEditMirrored
    icEducation
    icEducationIcon
    icEject
    icEMI
    icEmoji
    icEmoji2
    icEmojiSwatch
    icEmojiTabCelebrationObjects
    icEmojiTabFavorites
    icEmojiTabFoodPlants
    icEmojiTabMoreSymbols
    icEmojiTabPeople
    icEmojiTabSmilesAnimals
    icEmojiTabSymbols
    icEmojiTabTextSmiles
    icEmojiTabTransitPlaces
    icEndPoint
    icEndPointSolid
    icEnglishPunctuation
    icEqualizer
    icEraseTool
    icEraseToolFill
    icEraseToolFill2
    icError
    icErrorBadge
    icErrorBadge12
    iceSIM
    iceSIMBusy
    iceSIMLocked
    iceSIMNoProfile
    icEthernet
    icEthernetError
    icEthernetWarning
    icExpandTile
    icExpandTileMirrored
    icExploitProtection
    icExploitProtectionSettings
    icExploreContent
    icExploreContentSingle
    icExport
    icExportMirrored
    icExpressiveInputEntry
    icEyedropper
    icEyeGaze
    icFamily
    icFastForward
    icFavicon
    icFavicon2
    icFavoriteList
    icFavoriteStar
    icFavoriteStarFill
    icFeedback
    icFeedbackApp
    icFerry
    icFerrySolid
    icFileExplorer
    icFileExplorerApp
    icFilter
    icFingerInking
    icFingerprint
    icFitPage
    icFlag
    icFlashlight
    icFlickDown
    icFlickLeft
    icFlickRight
    icFlickUp
    icFlow
    icFolder
    icFolderFill
    icFolderHorizontal
    icFolderOpen
    icFolderSelect
    icFont
    icFontColor
    icFontDecrease
    icFontIncrease
    icFontSize
    icForward
    icForwardCall
    icForwardMirrored
    icForwardSm
    icForwardSolidBold
    icFourBars
    icFreeFormClipping
    icFrigid
    icFull20
    icFullAlpha
    icFullCircleMask
    icFullHiragana
    icFullKatakana
    icFullScreen
    icFuzzyReading
    icGame
    icGameConsole
    icGenericScan
    icGIF
    icGiftboxOpen
    icGlobalNavigationButton
    icGlobe
    icGlobe2
    icGo
    icGoMirrored
    icGoToMessage
    icGoToStart
    icGotoToday
    icGridView
    icGripperBarHorizontal
    icGripperBarVertical
    icGripperResize
    icGripperResizeMirrored
    icGripperTool
    icGroceries
    icGroup
    icGroupList
    icGuestUser
    icHalfAlpha
    icHalfDullSound
    icHalfKatakana
    icHalfStarLeft
    icHalfStarRight
    icHandwriting
    icHandwriting20
    icHangUp
    icHardDrive
    icHeadlessDevice
    icHeadphone
    icHeadphone0
    icHeadphone1
    icHeadphone2
    icHeadphone3
    icHeadset
    icHealth
    icHeart
    icHeartBroken
    icHeartFill
    icHelp
    icHelpMirrored
    icHideBcc
    icHighlight
    icHighlightFill
    icHighlightFill2
    icHistory
    icHMD
    icHolePunchLandscapeBottom
    icHolePunchLandscapeLeft
    icHolePunchLandscapeRight
    icHolePunchLandscapeTop
    icHolePunchOff
    icHolePunchPortraitBottom
    icHolePunchPortraitLeft
    icHolePunchPortraitRight
    icHolePunchPortraitTop
    icHoloLensSelected
    icHome
    icHomeGroup
    icHomeSolid
    icHorizontalTabKey
    icHWPInsert
    icHWPJoin
    icHWPNewLine
    icHWPOverwrite
    icHWPScratchOut
    icHWPSplit
    icHWPStrikeThrough
    icIBeam
    icIBeamOutline
    icImageExport
    icImport
    icImportAll
    icImportAllMirrored
    icImportant
    icImportantBadge12
    icImportMirrored
    icIncidentTriangle
    icIncomingCall
    icInfo
    icInfo2
    icInfoSolid
    icInkingCaret
    icInkingColorFill
    icInkingColorOutline
    icInkingTool
    icInkingToolFill
    icInkingToolFill2
    icInPrivate
    icInputChr
    icInsiderHubApp
    icInstertWords
    icInstertWordsFill
    icInteractiveDashboard
    icInternetSharing
    icIOT
    icItalic
    icJapanese
    icJoinWords
    icJoinWordsFill
    icJpnRomanji
    icJpnRomanjiLock
    icJpnRomanjiShift
    icJpnRomanjiShiftLock
    icKey12On
    icKeyboard12Key
    icKeyboardBrightness
    icKeyboardClassic
    icKeyboardDismiss
    icKeyboardDock
    icKeyboardFull
    icKeyboardLeftAligned
    icKeyboardLeftDock
    icKeyboardLeftHanded
    icKeyboardLowerBrightness
    icKeyboardNarrow
    icKeyboardOneHanded
    icKeyboardRightAligned
    icKeyboardRightDock
    icKeyboardRightHanded
    icKeyboardSettings
    icKeyboardsettings20
    icKeyboardShortcut
    icKeyboardSplit
    icKeyboardStandard
    icKeyboardUndock
    icKiosk
    icKnowledgeArticle
    icKorean
    iclabel
    icLandscapeOrientation
    icLandscapeOrientationMirrored
    icLangJPN
    icLanguageChs
    icLanguageCht
    icLanguageJpn
    icLanguageKor
    icLaptopSecure
    icLaptopSelected
    icLargeErase
    icLeaf
    icLeaveChat
    icLeaveChatMirrored
    icLEDLight
    icLeftArrowKeyTime0
    icLeftDoubleQuote
    icLeftQuote
    icLeftStick
    icLexicon
    icLibrary
    icLight
    icLightbulb
    icLightningBolt
    icLikeChr
    icLikeDislike
    icLineDisplay
    icLink
    icList
    icListMirrored
    icLocaleLanguage
    icLocation
    icLockChr
    icLockFeedback
    icLockscreenDesktop
    icLockScreenGlance
    icLowerBrightness
    icMagStripeReader
    icMail
    icMailBadge12
    icMailFill
    icMailForward
    icMailForwardMirrored
    icMailReply
    icMailReplyAll
    icMailReplyAllMirrored
    icMailReplyMirrored
    icManage
    icMapCompassBottom
    icMapCompassTop
    icMapDirections
    icMapDrive
    icMapLayers
    icMapPin
    icMapPin2
    icMarker
    icMarket
    icMarquee
    icMedia
    icMediaStorageTower
    icMegaphone
    icMemo
    icMergeCall
    icMessage
    icMicClipping
    icMicError
    icMicOff
    icMicOff2
    icMicOn
    icMicrophone
    icMicrophoneListening
    icMicrophoneSolidBold
    icMicSleep
    icMiniContract2Mirrored
    icMiniExpand2Mirrored
    icMiracastLogoLarge
    icMiracastLogoSmall
    icMixedMediaBadge
    icMixVolumes
    icMobActionCenter
    icMobAirplane
    icMobBattery0
    icMobBattery1
    icMobBattery10
    icMobBattery2
    icMobBattery3
    icMobBattery4
    icMobBattery5
    icMobBattery6
    icMobBattery7
    icMobBattery8
    icMobBattery9
    icMobBatteryCharging0
    icMobBatteryCharging1
    icMobBatteryCharging10
    icMobBatteryCharging2
    icMobBatteryCharging3
    icMobBatteryCharging4
    icMobBatteryCharging5
    icMobBatteryCharging6
    icMobBatteryCharging7
    icMobBatteryCharging8
    icMobBatteryCharging9
    icMobBatterySaver0
    icMobBatterySaver1
    icMobBatterySaver10
    icMobBatterySaver2
    icMobBatterySaver3
    icMobBatterySaver4
    icMobBatterySaver5
    icMobBatterySaver6
    icMobBatterySaver7
    icMobBatterySaver8
    icMobBatterySaver9
    icMobBatteryUnknown
    icMobBluetooth
    icMobCallForwarding
    icMobCallForwardingMirrored
    icMobDrivingMode
    icMobeSIM
    icMobeSIMBusy
    icMobeSIMLocked
    icMobeSIMNoProfile
    icMobileLocked
    icMobileSelected
    icMobileTablet
    icMobLocation
    icMobQuietHours
    icMobSignal1
    icMobSignal2
    icMobSignal3
    icMobSignal4
    icMobSignal5
    icMobSIMError
    icMobSIMLock
    icMobSIMMissing
    icMobWifi1
    icMobWifi2
    icMobWifi3
    icMobWifi4
    icMobWifiHotspot
    icMobWifiWarning1
    icMobWifiWarning2
    icMobWifiWarning3
    icMobWifiWarning4
    icMore
    icMouse
    icMoveToFolder
    icMovies
    icMultimediaDMP
    icMultimediaDMS
    icMultimediaDVR
    icMultimediaPMP
    icMultiSelect
    icMultiSelectMirrored
    icMusicAlbum
    icMusicInfo
    icMusicNote
    icMusicSharing
    icMusicSharingOff
    icMute
    icMyNetwork
    icNarrator
    icNarratorApp
    icNarratorForward
    icNarratorForwardMirrored
    icNearbySharing
    icNetwork
    icNetworkAdapter
    icNetworkConnected
    icNetworkConnectedCheckmark
    icNetworkOffline
    icNetworkPhysical
    icNetworkPrinter
    icNetworkSharing
    icNetworkTower
    icNewFolder
    icNewWindow
    icNextChr
    icNoiseCancelation
    icNoiseCancelationOff
    icNUIFace
    icNUIFPContinueSlideAction
    icNUIFPContinueSlideHand
    icNUIFPPressAction
    icNUIFPPressHand
    icNUIFPPressRepeatAction
    icNUIFPPressRepeatHand
    icNUIFPRollLeftAction
    icNUIFPRollLeftHand
    icNUIFPRollRightHand
    icNUIFPRollRightHandAction
    icNUIFPStartSlideAction
    icNUIFPStartSlideHand
    icNUIIris
    icOEM
    icOneBar
    icOneHandedLeft20
    icOneHandedRight20
    icOpenFile
    icOpenFolderHorizontal
    icOpenInNewWindow
    icOpenLocal
    icOpenPane
    icOpenPaneMirrored
    icOpenWith
    icOpenWithMirrored
    icOrientation
    icOtherUser
    icOutlineHalfStarLeft
    icOutlineHalfStarRight
    icOutlineQuarterStarLeft
    icOutlineQuarterStarRight
    icOutlineStarLeftHalf
    icOutlineStarRightHalf
    icOutlineThreeQuarterStarLeft
    icOutlineThreeQuarterStarRight
    icOverwriteWords
    icOverwriteWordsFill
    icOverwriteWordsFillKorean
    icOverwriteWordsKorean
    icPackage
    icPage
    icPageLeft
    icPageMarginLandscapeModerate
    icPageMarginLandscapeNarrow
    icPageMarginLandscapeNormal
    icPageMarginLandscapeWide
    icPageMarginPortraitModerate
    icPageMarginPortraitNarrow
    icPageMarginPortraitNormal
    icPageMarginPortraitWide
    icPageMirrored
    icPageRight
    icPageSolid
    icPaginationDotOutline10
    icPaginationDotSolid10
    icPanMode
    icParkingLocation
    icParkingLocationMirrored
    icParkingLocationSolid
    icPartyLeader
    icPassiveAuthentication
    icPasswordKeyHide
    icPasswordKeyShow
    icPaste
    icPause
    icPauseBadge12
    icPauseBold
    icPaymentCard
    icPC1
    icPDF
    icPencil
    icPencilFill
    icPenPalette
    icPenPaletteMirrored
    icPenTips
    icPenTipsMirrored
    icPenWorkspace
    icPenWorkspaceMirrored
    icPeople
    icPeriodKey
    icPermissions
    icPersonalFolder
    icPersonalize
    icPhone
    icPhoneBook
    icPhoto
    icPhoto2
    icPicture
    icPieSingle
    icPin
    icPinFill
    icPinned
    icPinnedFill
    icPINPad
    icPinyinIMELogo
    icPLAP
    icPlay
    icPlay36
    icPlaybackRate1x
    icPlaybackRateOther
    icPlayBadge12
    icPlayerSettings
    icPlaySolid
    icPointErase
    icPointEraseMirrored
    icPointerHand
    icPoliceCar
    icPostUpdate
    icPowerButton
    icPowerButtonUpdate
    icPPSFourLandscape
    icPPSFourPortrait
    icPPSOneLandscape
    icPPSOnePortrait
    icPPSTwoLandscape
    icPPSTwoPortrait
    icPresenceChicklet
    icPresenceChickletVideo
    icPreview
    icPreviewLink
    icPrevious
    icPrintChr
    icPrintAllPages
    icPrintCustomRange
    icPrintDefault
    icPrinter3D
    icPrintfaxPrinterFile
    icPriority
    icPrivateCall
    icProcess
    icProcessing
    icProductivityMode
    icProgressRingDots
    icProject
    icProjector
    icProtectedDocument
    icProtractor
    icProvisioningPackage
    icPuncKey
    icPuncKey0
    icPuncKey1
    icPuncKey2
    icPuncKey3
    icPuncKey4
    icPuncKey5
    icPuncKey6
    icPuncKey7
    icPuncKey8
    icPuncKey9
    icPuncKeyLeftBottom
    icPuncKeyRightBottom
    icPuzzle
    icQRCode
    icQuarentinedItems
    icQuarentinedItemsMirrored
    icQuarterStarLeft
    icQuarterStarRight
    icQuickNote
    icQuietHours
    icQuietHoursBadge12
    icQWERTYOff
    icQWERTYOn
    icRadar
    icRadioBtnOff
    icRadioBtnOn
    icRadioBullet
    icRadioBullet2
    icRead
    icReadingList
    icReadingMode
    icReceiptPrinter
    icRecent
    icRecord
    icRecord2
    icRectangularClipping
    icRedEye
    icRedo
    icRefresh
    icRelationship
    icRememberedDevice
    icReminder
    icReminderFill
    icRemote
    icRemove
    icRemoveFrom
    icRename
    icRepair
    icRepeatAll
    icRepeatOff
    icRepeatOne
    icReplay
    icReply
    icReplyMirrored
    icReportDocument
    icReportHacked
    icResetDevice
    icResetDrive
    icReshare
    icResizeMouseLarge
    icResizeMouseMedium
    icResizeMouseMediumMirrored
    icResizeMouseSmall
    icResizeMouseSmallMirrored
    icResizeMouseTall
    icResizeMouseTallMirrored
    icResizeMouseWide
    icResizeTouchLarger
    icResizeTouchNarrower
    icResizeTouchNarrowerMirrored
    icResizeTouchShorter
    icResizeTouchSmaller
    icRestartUpdate
    icReturnKey
    icReturnKeyLg
    icReturnKeySm
    icReturnToCall
    icReturnToWindow
    icRevealPasswordMedium
    icRevToggleKey
    icRewind
    icRightArrowKeyTime0
    icRightArrowKeyTime1
    icRightArrowKeyTime2
    icRightArrowKeyTime3
    icRightArrowKeyTime4
    icRightDoubleQuote
    icRightQuote
    icRightStick
    icRinger
    icRingerBadge12
    icRingerSilent
    icRoamingDomestic
    icRoamingInternational
    icRobot
    icRotate
    icRotateCamera
    icRotateMapLeft
    icRotateMapRight
    icRotationLock
    icRTTLogo
    icRuler
    icSafe
    icSave
    icSaveAs
    icSaveCopy
    icSaveLocal
    icScan
    icScreenTime
    icScrollMode
    icScrollUpDown
    icSDCard
    icSearch
    icSearchAndApps
    icSearchMedium
    icSelectAll
    icSend
    icSendFill
    icSendFillMirrored
    icSendMirrored
    icSensor
    icSetChr
    icSetHistoryStatus
    icSetHistoryStatus2
    icSetlockScreen
    icSetSolid
    icSetTile
    icSetting
    icSettingsBattery
    icSettingsDisplaySound
    icSettingsSolid
    icShare
    icShareBroadband
    icShield
    icShop
    icShoppingCart
    icShowBcc
    icShowResults
    icShowResultsMirrored
    icShuffle
    icSignalBars1
    icSignalBars2
    icSignalBars3
    icSignalBars4
    icSignalBars5
    icSignalError
    icSignalNotConnected
    icSignalRoaming
    icSignatureCapture
    icSignOut
    icSIMError
    icSIMLock
    icSIMMissing
    icSingleLandscape
    icSinglePortrait
    icSIPMove
    icSIPRedock
    icSIPUndock
    icSkipBack10
    icSkipForward30
    icSliderThumb
    icSlideshow
    icSlowMotionOn
    icSmallErase
    icSmartcard
    icSmartcardVirtual
    icSmartScreen
    icSort
    icSpatialVolume0
    icSpatialVolume1
    icSpatialVolume2
    icSpatialVolume3
    icSpeakers
    icSpecialEffectSize
    icSpeech
    icSpeechSolidBold
    icSpeedHigh
    icSpeedMedium
    icSpeedOff
    icSpelling
    icSpellingChinese
    icSpellingKorean
    icSpellingSerbian
    icSplit20
    icStaplingLandscapeBookBinding
    icStaplingLandscapeBottomLeft
    icStaplingLandscapeBottomRight
    icStaplingLandscapeTopLeft
    icStaplingLandscapeTopRight
    icStaplingLandscapeTwoBottom
    icStaplingLandscapeTwoLeft
    icStaplingLandscapeTwoRight
    icStaplingLandscapeTwoTop
    icStaplingOff
    icStaplingPortraitBookBinding
    icStaplingPortraitBottomLeft
    icStaplingPortraitBottomRight
    icStaplingPortraitTopLeft
    icStaplingPortraitTopRight
    icStaplingPortraitTwoBottom
    icStaplingPortraitTwoLeft
    icStaplingPortraitTwoRight
    icStaplingPortraitTwoTop
    icStartPoint
    icStartPointSolid
    icStartPresenting
    icStatusCheckmark
    icStatusCheckmark7
    icStatusCheckmarkLeft
    icStatusCircle
    icStatusCircle7
    icStatusCircleBlock
    icStatusCircleBlock2
    icStatusCircleCheckmark
    icStatusCircleErrorX
    icStatusCircleExclamation
    icStatusCircleInfo
    icStatusCircleInner
    icStatusCircleLeft
    icStatusCircleOuter
    icStatusCircleQuestionMark
    icStatusCircleRing
    icStatusCircleSync
    icStatusConnecting1
    icStatusConnecting2
    icStatusDataTransfer
    icStatusDataTransferRoaming
    icStatusDataTransferVPN
    icStatusDualSIM1
    icStatusDualSIM1VPN
    icStatusDualSIM2
    icStatusDualSIM2VPN
    icStatusError
    icStatusErrorCircle7
    icStatusErrorFull
    icStatusErrorLeft
    icStatusExclamationCircle7
    icStatusInfo
    icStatusInfoLeft
    icStatusPause7
    icStatusSecured
    icStatusSGLTE
    icStatusSGLTECell
    icStatusSGLTEDataVPN
    icStatusTriangle
    icStatusTriangleExclamation
    icStatusTriangleInner
    icStatusTriangleLeft
    icStatusTriangleOuter
    icStatusUnsecure
    icStatusVPN
    icStatusWarning
    icStatusWarningLeft
    icSticker2
    icStockDown
    icStockUp
    icStopChr
    icStopPoint
    icStopPointSolid
    icStopPresenting
    icStopwatch
    icStorageNetworkWireless
    icStorageOptical
    icStorageTape
    icStreaming
    icStreamingEnterprise
    icStreet
    icStreetsideSplitExpand
    icStreetsideSplitMinimize
    icStrikethrough
    icStrokeErase
    icStrokeErase2
    icStrokeEraseMirrored
    icSubscriptionAdd
    icSubscriptionAddMirrored
    icSubtitles
    icSubtitlesAudio
    icSubtractBold
    icSurfaceHub
    icSurfaceHubSelected
    icSustainable
    icSwipe
    icSwipeRevealArt
    icSwitch
    icSwitchApps
    icSwitchUser
    icSync
    icSyncBadge12
    icSyncError
    icSyncFolder
    icSystem
    icTablet
    icTabletMode
    icTabletSelected
    icTag
    icTapAndSend
    icTaskbarPhone
    icTaskView
    icTaskViewExpanded
    icTaskViewSettings
    icThisPC
    icThoughtBubble
    icThreeBars
    icThreeQuarterStarLeft
    icThreeQuarterStarRight
    icTiles
    icTiltDown
    icTiltUp
    icTimeLanguage
    icToggleBorder
    icToggleFilled
    icToggleLeft
    icToggleRight
    icToggleThumb
    icTollSolid
    icToolTip
    icTouch
    icTouchpad
    icTouchPointer
    icTouchscreen
    icTrackers
    icTrackersMirrored
    icTrafficCongestionSolid
    icTrafficLight
    icTrain
    icTrainSolid
    icTreeFolderFolder
    icTreeFolderFolderFill
    icTreeFolderFolderOpen
    icTreeFolderFolderOpenFill
    icTriggerLeft
    icTriggerRight
    icTrim
    icTVMonitor
    icTVMonitorSelected
    icTwoBars
    icTwoPage
    icTypeChr
    icUnderline
    icUnderscoreSpace
    icUndo
    icUnfavorite
    icUnit
    icUnknown
    icUnknownMirrored
    icUnlockChr
    icUnpin
    icUnsyncFolder
    icUp
    icUpArrowShiftKey
    icUpdateRestore
    icUpdateStatusDot
    icUpload
    icUpShiftKey
    icUSB
    icUSBSafeConnect
    icUserAPN
    icVerticalBattery0
    icVerticalBattery1
    icVerticalBattery10
    icVerticalBattery2
    icVerticalBattery3
    icVerticalBattery4
    icVerticalBattery5
    icVerticalBattery6
    icVerticalBattery7
    icVerticalBattery8
    icVerticalBattery9
    icVerticalBatteryCharging0
    icVerticalBatteryCharging1
    icVerticalBatteryCharging10
    icVerticalBatteryCharging2
    icVerticalBatteryCharging3
    icVerticalBatteryCharging4
    icVerticalBatteryCharging5
    icVerticalBatteryCharging6
    icVerticalBatteryCharging7
    icVerticalBatteryCharging8
    icVerticalBatteryCharging9
    icVerticalBatteryUnknown
    icVibrate
    icVideo
    icVideo360
    icVideoCapture
    icVideoChat
    icVideoSolid
    icView
    icViewAll
    icViewDashboard
    icVirtualMachineGroup
    icVoiceCall
    icVolume
    icVolume0
    icVolume1
    icVolume2
    icVolume3
    icVolumeBars
    icVPN
    icWalk
    icWalkSolid
    icWarning
    icWebcam
    icWebcam2
    icWebSearch
    icWebsite
    icWheel
    icWifi
    icWifi1
    icWifi2
    icWifi3
    icWifiAttentionOverlay
    icWifiCall0Chr
    icWifiCall0
    icWifiCall1Chr
    icWifiCall1
    icWifiCall2Chr
    icWifiCall2
    icWifiCall3Chr
    icWifiCall3
    icWifiCall4Chr
    icWifiCall4
    icWifiCallBarsChr
    icWifiCallBars
    icWifiError0
    icWifiError1
    icWifiError2
    icWifiError3
    icWifiError4
    icWifiEthernet
    icWifiHotspot
    icWifiWarning0
    icWifiWarning1
    icWifiWarning2
    icWifiWarning3
    icWifiWarning4
    icWindDirection
    icWindowsInsider
    icWindowSnipping
    icWire
    icWiredUSB
    icWirelessUSB
    icWork
    icWorkSolid
    icWorld
    icXboxOneConsole
    icZeroBars
    icZoom
    icZoomIn
    icZoomMode
    icZoomOut
    [_First] = icAccept
    [_Last] = icZoomOut
End Enum

Private Enum colNameEnum
    NameIcon = 1
    CodeIcon
    CharIcon
End Enum

Public Function getIcon(ByVal codIcon As IconEnums) As String
    getIcon = VBA.ChrW$(getIconCode(codIcon))
End Function

Public Function getIconCode(ByVal codIcon As IconEnums) As Long
    getIconCode = getIconCodeOrName(codIcon, colNameEnum.CodeIcon)
End Function

Public Function getIconName(ByVal codIcon As IconEnums) As String
    getIconName = getIconCodeOrName(codIcon, colNameEnum.NameIcon)
End Function

Public Function getAllIconsArray() As Variant
    Dim sh          As Worksheet
    Const SH_NAME   As String = "ICON"
    If HaveSheetInFile(ThisWorkbook, SH_NAME) Then
        Set sh = ThisWorkbook.Worksheets(SH_NAME)
    Else
        If wbIsOpen("MACROTools.xlam") Then
            Dim arr As Variant
            arr = Workbooks("MACROTools.xlam").Worksheets("SHSNIPPETS").ListObjects(TB_ICON).Range.Value2
            Set sh = ThisWorkbook.Worksheets.Add
            With sh
                .Name = SH_NAME
                .Cells(1, 1).Resize(UBound(arr, 1), UBound(arr, 2)).Value2 = arr
                With .ListObjects.Add(xlSrcRange, .Cells(1, 1).Resize(UBound(arr, 1), UBound(arr, 2)), , xlYes)
                    .Name = TB_ICON
                    With .ListColumns(3).DataBodyRange
                        .Font.Name = "Segoe MDL2 Assets"
                        .HorizontalAlignment = xlCenter
                    End With
                End With
                .Columns(1).EntireColumn.AutoFit
                .Columns(2).EntireColumn.AutoFit
                .Columns(3).EntireColumn.AutoFit
            End With
        Else
            getAllIconsArray = -1
            Exit Function
        End If
    End If

    With sh.ListObjects(TB_ICON)
        If Not .DataBodyRange Is Nothing Then getAllIconsArray = .DataBodyRange.Value2
    End With
End Function

Private Function HaveSheetInFile(ByRef wb As Workbook, ByVal SHName As String) As Boolean
    Dim sh          As Worksheet
    On Error Resume Next
    Set sh = wb.Worksheets(SHName)
    HaveSheetInFile = Err.Number = 0
    Err.Clear
End Function

Private Function wbIsOpen(ByVal sNameWb As String) As Boolean
    On Error Resume Next
    Dim wb          As Workbook
    Set wb = Workbooks(sNameWb)
    wbIsOpen = Err.Number = 0
    Err.Clear
End Function

Private Function getIconCodeOrName(ByVal codIcon As IconEnums, ByVal iCol As colNameEnum) As Variant
    Select Case codIcon
        Case Is < IconEnums.[_First]:
            Err.Raise Number:=vbObjectError + 1, Description:="The codIcon can't be less than: [ " & IconEnums.[_First] & " ], your value [ " & codIcon & " ]"
        Case Is > IconEnums.[_Last]:
            Err.Raise Number:=vbObjectError + 2, Description:="The codIcon can't be more than: [ " & IconEnums.[_Last] & " ], your value [ " & codIcon & " ]"
        Case Else:
            Dim arrIcon As Variant
            arrIcon = getAllIconsArray()
            If IsArray(arrIcon) Then
                getIconCodeOrName = arrIcon(codIcon, iCol)
            ElseIf arrIcon = -1 Then
                Err.Raise Number:=vbObjectError + 3, Description:="The source of the icon array was not found"
            End If
    End Select
End Function
